// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Aiqx1k3hf8N04PB90qkNesHHnS4PFk4',
    appId: '1:686643457853:web:d4249e5e361c650aa39f54',
    messagingSenderId: '686643457853',
    projectId: 'tubes-mobile2',
    authDomain: 'tubes-mobile2.firebaseapp.com',
    storageBucket: 'tubes-mobile2.appspot.com',
    measurementId: 'G-3X29PE821D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzlDeqYBVyahWyMeSoggT2LkfrauoqV5Y',
    appId: '1:686643457853:android:5fe482cf84518f88a39f54',
    messagingSenderId: '686643457853',
    projectId: 'tubes-mobile2',
    storageBucket: 'tubes-mobile2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDixxw0c8BIHcTX_t9Hrcz4fhF6RJSUE',
    appId: '1:686643457853:ios:a2a3e0d62d3d2e09a39f54',
    messagingSenderId: '686643457853',
    projectId: 'tubes-mobile2',
    storageBucket: 'tubes-mobile2.appspot.com',
    iosBundleId: 'com.example.tubesPpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDixxw0c8BIHcTX_t9Hrcz4fhF6RJSUE',
    appId: '1:686643457853:ios:d82a13699ce7b3cea39f54',
    messagingSenderId: '686643457853',
    projectId: 'tubes-mobile2',
    storageBucket: 'tubes-mobile2.appspot.com',
    iosBundleId: 'com.example.tubesPpb.RunnerTests',
  );
}
